### PR TITLE
Reformat according to the Plone styleguide while reading.

### PR DESCRIPTION
**Pull request by thet**
@gforcada What's the procedure of having here a QA setup for Jenkins? From now on, this should be style-checked.

### CODE REVIEW

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/885/

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/886/

**Comment by gforcada** [comment]
@thet do you want me to turn on the automatic code analysis on jenkins for plone.indexer?

**Comment by thet** [comment]
Yes please! And merge this one, if you're ok with it :)

**Comment by gforcada** [comment]
@thet as soon as jenkins says so :-)

The code analysis is in, you will probably get a message in this pull request already.

**Comment by thet** [comment]
@gforcada done, except some hard nuts.

**Pull request merged**
